services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=monolito'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    